# Generated by Django 4.1.7 on 2023-02-23 12:52

from django.db import migrations, models
import django.db.models.deletion
import transactions.custom_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('INITIATED', 'Initiated'), ('SUCCESSFUL', 'Successful'), ('RETURNED', 'Returned'), ('CANCELLED', 'Cancelled')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=255)),
                ('gross_amount', transactions.custom_fields.CurrencyField(decimal_places=2, max_digits=10)),
                ('swifter_id', models.CharField(max_length=6)),
                ('external_id', models.CharField(max_length=6)),
                ('source', models.CharField(choices=[('PAYMENTS', 'Payments'), ('E-COMMERCE', 'E-commerce'), ('IN-STORE', 'In-store')], max_length=30)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='transactions.status')),
            ],
        ),
    ]
